security:
    encoders:
        "FOS\UserBundle\Model\UserInterface": sha512

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: delete/$|delete$, role: ROLE_ADMIN }
        - { path: ^/admin/blog/, role: ROLE_INNKEEPER }
        - { path: ^/admin/, role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_INNKEEPER:   ROLE_USER
        ROLE_ADMIN:       ROLE_INNKEEPER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
